export const START_RECIPES_FETCHING = 'START_RECIPES_FETCHING';
export const CHANGE_CURRENT_GOAL = 'CHANGE_CURRENT_GOAL';
export const RECIPES_FETCHED = 'RECIPES_FETCHED';
export const RECIPES_FETCHING_ERROR_OCCURED = 'RECIPES_FETCHING_ERROR_OCCURED';
